# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tyler/Documents/csci-3010/Homework/csci-3010-hw4/chutes_and_ladders/playerdiag.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_playerDiag(object):
    def setupUi(self, playerDiag):
        playerDiag.setObjectName("playerDiag")
        playerDiag.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(playerDiag)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(playerDiag)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLabel = QtWidgets.QLabel(playerDiag)
        self.leftLabel.setObjectName("leftLabel")
        self.horizontalLayout.addWidget(self.leftLabel)
        self.playerSlider = QtWidgets.QSlider(playerDiag)
        self.playerSlider.setMinimum(2)
        self.playerSlider.setMaximum(4)
        self.playerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playerSlider.setObjectName("playerSlider")
        self.horizontalLayout.addWidget(self.playerSlider)
        self.rightLabel = QtWidgets.QLabel(playerDiag)
        self.rightLabel.setObjectName("rightLabel")
        self.horizontalLayout.addWidget(self.rightLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.submitBut = QtWidgets.QPushButton(playerDiag)
        self.submitBut.setObjectName("submitBut")
        self.verticalLayout.addWidget(self.submitBut)

        self.retranslateUi(playerDiag)
        QtCore.QMetaObject.connectSlotsByName(playerDiag)

    def retranslateUi(self, playerDiag):
        _translate = QtCore.QCoreApplication.translate
        playerDiag.setWindowTitle(_translate("playerDiag", "Dialog"))
        self.label.setText(_translate("playerDiag", "Select Number of Players"))
        self.leftLabel.setText(_translate("playerDiag", "2"))
        self.rightLabel.setText(_translate("playerDiag", "4"))
        self.submitBut.setText(_translate("playerDiag", "Submit"))
